stages:
  - container
  - cluster

build-job:      
  stage: container
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: ""
  tags:
    - k8s-runner
  image: docker:20.10.7
  services:
    - docker:20.10.7-dind
  script:
    - docker build -t camillamartins/dockernode:$CI_PIPELINE_ID .
    - docker push camillamartins/dockernode:$CI_PIPELINE_ID

cluster:
  image: bitnami/kubectl
  stage: cluster
  tags:
    - k8s-runner
  script:
    - kubectl apply -f deployment.yaml
