runners:
  config: |
    [[runners]]
      [runners.docker]
        tls_verify = false
        image = "docker:19.03.12"
        privileged = false
        disable_cache = false
        volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/cache"]
      [runners.cache]
        Insecure = false

gitlabUrl: "https://gitlab.com/"

runnerRegistrationToken: "-VG7DG91zvWWF-BLoPcK"

## helpers:
##    cpuLimit: 200m