runners:
  config: |
    [[runners]]
      [runners.kubernetes]
        image = "ubuntu:16.04"
        helper_cpu_limit = "200m"
        privileged = true
      [[runners.kubernetes.volumes.host_path]]
        name = "docker"
        mount_path = "/var/run/docker.sock"
        path = "/var/run/docker.sock"

gitlabUrl: "https://gitlab.com/"

runnerRegistrationToken: "-VG7DG91zvWWF-BLoPcK"

## helpers:
##    cpuLimit: 200m